version: '3.8'

services:
  mcp-powerpoint-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./output:/app/output
    restart: unless-stopped
